## Importar Librerias:

In [2]:
import pandas as pd
import matplotlib as plt

## Importar/leer Data Sets:

**Se cargaron todos los data sets del curso y se les asigno un nombre de variable**

In [3]:
happiness = pd.read_csv("DataSets/2018-2019+Happiness.csv")
airbnb = pd.read_csv("DataSets/airbnb.csv")
ethereum = pd.read_csv("DataSets/Ethereum+Historical+Data.csv")
salaries = pd.read_csv("DataSets/salaries.csv")

## Previw de cada data set

In [4]:
happiness

,Overall rank,Year,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,2019,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,2019,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,2019,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,2019,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,2019,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...,...
307,152,2018,Yemen,3.355,0.442,1.073,0.343,0.244,0.083,0.064
308,153,2018,Tanzania,3.303,0.455,0.991,0.381,0.481,0.270,0.097
309,154,2018,South Sudan,3.254,0.337,0.608,0.177,0.112,0.224,0.106
310,155,2018,Central African Republic,3.083,0.024,0.000,0.010,0.305,0.218,0.038
311,156,2018,Burundi,2.905,0.091,0.627,0.145,0.065,0.149,0.076

In [9]:
airbnb.head(10) #carga los primeros n (en este caso 10) datos

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,26/06/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,26/06/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0
5,1039,25/07/2008,Big Greenpoint 1BD w/ Skyline View,Brooklyn,Apartment,100.0,Entire home/apt,11222.0,1.0,1,4,149,100.0
6,1783,12/08/2008,Amazing Also,Manhattan,Apartment,100.0,Entire home/apt,10004.0,1.0,1,9,250,100.0
7,2078,15/08/2008,"Colorful, quiet, & near the subway!",Brooklyn,Apartment,90.0,Private room,11201.0,1.0,1,80,90,94.0
8,2339,20/08/2008,East Village Cocoon: 2 Bedroom Flat,Manhattan,Apartment,90.0,Entire home/apt,10009.0,2.0,1,95,270,90.0
9,2339,20/08/2008,Lovely 2 Bedroom East Village Nest,Manhattan,Apartment,95.0,Entire home/apt,10009.0,2.0,1,23,290,96.0

In [8]:
ethereum.tail(10) #carga los ultimos n (en este caso 10) datos

            Date Coin   Price    Open    High     Low    Vol. Change %
1492  10/01/2020  ETH  144.81  137.93  144.86  135.69  13.37M    4.99%
1493   9/01/2020  ETH  137.92  140.80  141.60  135.85  11.38M   -2.05%
1494   8/01/2020  ETH  140.81  143.01  147.55  137.61  13.71M   -1.56%
1495   7/01/2020  ETH  143.04  144.09  145.13  139.22  13.58M   -0.73%
1496   6/01/2020  ETH  144.08  135.59  144.27  135.17  14.36M    6.26%
1497   5/01/2020  ETH  135.59  134.32  138.33  134.32  12.19M    0.94%
1498   4/01/2020  ETH  134.33  134.30  135.57  132.76  11.16M    0.04%
1499   3/01/2020  ETH  134.27  127.19  134.86  126.05  15.67M    5.56%
1500   2/01/2020  ETH  127.19  130.75  130.77  126.74  11.45M   -2.72%
1501   1/01/2020  ETH  130.75  129.21  132.97  128.81  10.35M    1.19%

In [7]:
salaries.head() #Si los parentesis no se llenan el default son 5 resultados, sea funcion tail o head

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,EX,FT,Data Science Director,212000,USD,212000,US,0,US,M
1,2023,EX,FT,Data Science Director,190000,USD,190000,US,0,US,M
2,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
3,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
4,2023,SE,FT,Machine Learning Engineer,245700,USD,245700,US,0,US,M

## Ver informacion del data set (columna, cuantos nulos hay  y data type)

In [12]:
salaries.info() #Funcion info carga la info del data frame, si no se ponen los parentesis te carga cada columna y sus registros

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8805 entries, 0 to 8804
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   work_year           8805 non-null   int64
 1   experience_level    8805 non-null   object
 2   employment_type     8805 non-null   object
 3   job_title           8805 non-null   object
 4   salary              8805 non-null   int64
 5   salary_currency     8805 non-null   object
 6   salary_in_usd       8805 non-null   int64
 7   employee_residence  8805 non-null   object
 8   remote_ratio        8805 non-null   int64
 9   company_location    8805 non-null   object
 10  company_size        8805 non-null   object
dtypes: int64(4), object(7)
memory usage: 756.8+ KB

In [13]:
salaries.info #Resultado sin parentesis

<bound method DataFrame.info of       work_year experience_level employment_type  \
0          2023               EX              FT
1          2023               EX              FT
2          2023               MI              FT
3          2023               MI              FT
4          2023               SE              FT
...         ...              ...             ...
8800       2020               SE              FT
8801       2021               MI              FT
8802       2020               EN              FT
8803       2020               EN              CT
8804       2021               SE              FT

                           job_title   salary salary_currency  salary_in_usd  \
0              Data Science Director   212000             USD         212000
1              Data Science Director   190000             USD         190000
2     Business Intelligence Engineer    35000             GBP          43064
3     Business Intelligence Engineer    35000             GBP          43064
4          Machine Learning Engineer   245700             USD         245700
...                              ...      ...             ...            ...
8800                  Data Scientist   412000             USD         412000
8801        Principal Data Scientist   151000             USD         151000
8802                  Data Scientist   105000             USD         105000
8803           Business Data Analyst   100000             USD         100000
8804            Data Science Manager  7000000             INR          94665

     employee_residence  remote_ratio company_location company_size
0                    US             0               US            M
1                    US             0               US            M
2                    GB             0               GB            M
3                    GB             0               GB            M
4                    US             0               US            M
...                 ...           ...              ...          ...
8800                 US           100               US            L
8801                 US           100               US            L
8802                 US           100               US            S
8803                 US           100               US            L
8804                 IN            50               IN            L

[8805 rows x 11 columns]>

In [19]:
salaries.shape #muestra cantidad de filas y de columnas en el data set respectivamente

(8805, 11)

In [20]:
salaries.size #muestra la canmtidad de elementos en el dataframe (La cantidad se obtiene multiplicando columnas por filas)

96855

In [21]:
salaries.columns #Muestra los nombres de las columnas del dataframe

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

## Cambiar nombres columnas data set

*Para cambiar los nombres de las columnas lo mas facil es usar la fucion columns, para ver el nombre de las columnas, luego copiar esos datos
en una nueva variable y cambiar en la variablers los nombres, hecho esto, usas el comando para cargar el data set, poniendo una coma seguido de
**names = [nombre de tu variable]** sin brackets, luego de esto, debes especificar la fila en la que estan los headers del csv (Usualmente la 0),
esto se hace poniendo una coma despues de la variable con los nombres, seguido de <br>
**header = Numero de columna en que estan los headers***
<br>

**Por ejemplo:**

_______________________________________________________________________________________________________________________________________________________

In [23]:
salaries.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [24]:
NuevosNombres = ['Ano_Trabajo', 'Experiencia', 'Tipo_empleado', 'Titulo_profesional',
       'Sueldo', 'Moneda_sueldo', 'Sueldo_USD', 'Recidencia_Empleado',
       'remote_ratio', 'Ubicacion_compania', 'Tamano_Compania']

In [27]:
salariesNew = pd.read_csv("DataSets/salaries.csv", names = NuevosNombres, header = 0)

In [28]:
salariesNew

,Ano_Trabajo,Experiencia,Tipo_empleado,Titulo_profesional,Sueldo,Moneda_sueldo,Sueldo_USD,Recidencia_Empleado,remote_ratio,Ubicacion_compania,Tamano_Compania
0,2023,EX,FT,Data Science Director,212000,USD,212000,US,0,US,M
1,2023,EX,FT,Data Science Director,190000,USD,190000,US,0,US,M
2,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
3,2023,MI,FT,Business Intelligence Engineer,35000,GBP,43064,GB,0,GB,M
4,2023,SE,FT,Machine Learning Engineer,245700,USD,245700,US,0,US,M
...,...,...,...,...,...,...,...,...,...,...,...
8800,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L
8801,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L
8802,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S
8803,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L
8804,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L